const menuButton=document.querySelector('.menu-btn');const nav=document.querySelector('nav');menuButton?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('nav a').forEach(link=>link.addEventListener('click',()=>nav.classList.remove('open')));const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const vehicleLabels={coupe:'Coupe',sedan:'Sedan',crossover:'Crossover / Small Truck',large:'Van / Truck / SUV',utility:'Utility Truck / Work Van'};
const tiers={
1:{name:'Essential Detail',description:'The base mobile detail for a clean, refreshed vehicle inside and out.',services:['Bug removal','Hand wash','Door jambs cleaned','Tires dressed','Microfiber towel drying','Windows cleaned and wiped down','Full vacuum and blowout','Interior wipedown'],prices:{coupe:90,sedan:100,crossover:110,large:120,utility:130}},
2:{name:'Enhanced Detail',description:'A stronger maintenance detail that adds protection and more focused interior care.',services:['Everything in Tier 1','Wax','Seats scrubbed','Floor mats shampooed / extracted','Rubber mats pressure washed and dressed','Vents blown out'],prices:{coupe:130,sedan:150,crossover:160,large:170,utility:180}},
3:{name:'Deep Detail',description:'The advanced, most-popular deep-clean package for significantly more interior restoration.',services:['Everything in Tier 2','Cloth seats steamed, shampooed and extracted','Leather seats conditioned','Headliner carefully scrubbed / wiped down','Flooring steamed, shampooed and extracted','Vents steam cleaned'],prices:{coupe:220,sedan:250,crossover:260,large:270,utility:280}},
4:{name:'Signature Detail',description:'The highest-level complete detail with engine bay, wheel wells and trim finishing.',services:['Everything in Tier 3','Engine bay cleaned and dressed','Trim dressed','Wheel wells dressed','Highest-attention final inspection'],prices:{coupe:280,sedan:300,crossover:310,large:320,utility:330}}
};
const premiumPrices={paint:{coupe:250,sedan:300,crossover:350,large:400,utility:450},ceramic:{coupe:800,sedan:900,crossover:950,large:1000,utility:1100}};
let vehicleType='coupe';const packageSelect=document.querySelector('#packageSelect');
function renderTier(tier){const data=tiers[tier];document.getElementById('tierLabel').textContent=`TIER ${tier} DETAIL`;document.getElementById('tierName').textContent=data.name;document.getElementById('tierDescription').textContent=data.description;document.getElementById('tierServices').innerHTML=data.services.map(s=>`<li>${s}</li>`).join('');document.getElementById('priceTable').innerHTML=Object.entries(data.prices).map(([key,value])=>`<div class="price-row"><span>${vehicleLabels[key]}</span><strong>$${value}</strong></div>`).join('');document.querySelectorAll('.tier-tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.tier===String(tier)))}
function basePrice(){const service=packageSelect.value;if(service==='paint'||service==='ceramic')return premiumPrices[service][vehicleType];return tiers[service].prices[vehicleType]}
function calculate(){let total=basePrice();document.querySelectorAll('.addons input:checked').forEach(input=>total+=Number(input.value));['estimate','estimateBottom','buttonPrice'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=`$${total.toLocaleString()}`});return total}
document.querySelectorAll('.tier-tab').forEach(btn=>btn.addEventListener('click',()=>{renderTier(btn.dataset.tier);packageSelect.value=btn.dataset.tier;calculate()}));
document.querySelectorAll('.vehicle').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.vehicle').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');vehicleType=button.dataset.vehicle;calculate()}));
packageSelect?.addEventListener('change',()=>{if(tiers[packageSelect.value])renderTier(packageSelect.value);calculate()});document.querySelectorAll('.addons input').forEach(input=>input.addEventListener('change',calculate));
document.querySelectorAll('.service-select').forEach(button=>button.addEventListener('click',()=>{packageSelect.value=button.dataset.service==='Paint Correction'?'paint':'ceramic';calculate();document.querySelector('#book').scrollIntoView({behavior:'smooth'})}));
document.querySelector('#bookingForm')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const addons=[...document.querySelectorAll('.addons input:checked')].map(x=>x.dataset.label).join(', ')||'None';const total=calculate();const serviceValue=data.get('package');const serviceName=serviceValue==='paint'?'Paint Correction':serviceValue==='ceramic'?'Ceramic Coating':`Tier ${serviceValue} ${tiers[serviceValue].name}`;const message=`Hi Raydonous, I'd like to request a mobile service.%0A%0AName: ${encodeURIComponent(data.get('name'))}%0APhone: ${encodeURIComponent(data.get('phone'))}%0AEmail: ${encodeURIComponent(data.get('email')||'Not provided')}%0AVehicle: ${encodeURIComponent(data.get('vehicle'))}%0AVehicle size: ${encodeURIComponent(vehicleLabels[vehicleType])}%0AService: ${encodeURIComponent(serviceName)}%0AAdd-ons: ${encodeURIComponent(addons)}%0AEstimated total: $${total}%0APreferred date: ${encodeURIComponent(data.get('date'))}%0APreferred time: ${encodeURIComponent(data.get('time'))}%0AService address: ${encodeURIComponent(data.get('address'))}%0ANotes: ${encodeURIComponent(data.get('details')||'None')}%0A%0AI understand this is an estimate and Ray will confirm final pricing.`;window.location.href=`sms:+18132939734?&body=${message}`});document.querySelector('#year').textContent=new Date().getFullYear();renderTier(1);calculate();